[package]
name = "hal-back-wepapp"
version = "0.0.1"
edition = "2018"

[dependencies]
rocket = "0.4.10" 

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["serve", "diesel_sqlite_pool"]

[dependencies.rusqlite]
version = "0.14.0"
features = ["bundled"]
